---
abstract: 'A Perl interface to the United States Office of Foreign Assets'
author:
  - 'tyler hardison <tyler@seraph-net.net>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-OFAC
no_index:
  directory:
    - t
    - inc
requires:
  Archive::Extract: 0
  Archive::Zip: 0
  DBD::SQLite: 0
  DBIx::Class::PhoneticSearch: 0
  DBIx::Class::Schema: 0
  LWP: 0
  Text::CSV: 0
  perl: 5.006
version: 0.65
